export const RACE_LIVE_EVENT_TYPES = Object.freeze({
  PLAYER_JOINED: "PLAYER_JOINED",
  RACE_STARTED: "RACE_STARTED",
  QUESTION_ANSWERED: "QUESTION_ANSWERED",
  PLAYER_PROGRESS_UPDATED: "PLAYER_PROGRESS_UPDATED",
  PLAYER_FINISHED: "PLAYER_FINISHED",
  RACE_FINISHED: "RACE_FINISHED",
});
