export const TEACHER_LIVE_EVENT_OUTCOMES = Object.freeze({
  APPLIED: "APPLIED",
  STALE: "STALE",
  RECOVERY_REQUIRED: "RECOVERY_REQUIRED",
});

export const TEACHER_LIVE_RECOVERY_REASONS = Object.freeze({
  RACE_MISMATCH: "RACE_MISMATCH",
  VERSION_GAP: "VERSION_GAP",
  MALFORMED_PAYLOAD: "MALFORMED_PAYLOAD",
  MALFORMED_EVENT: "MALFORMED_EVENT",
  STREAM_CLOSED: "STREAM_CLOSED",
  RECONNECT_TIMEOUT: "RECONNECT_TIMEOUT",
  BROWSER_ONLINE: "BROWSER_ONLINE",
});

export const TEACHER_STREAM_STATUSES = Object.freeze({
  IDLE: "IDLE",
  OPENING: "OPENING",
  OPEN: "OPEN",
  RETRYING: "RETRYING",
});

export const TEACHER_CONNECTION_STATES = Object.freeze({
  CONNECTING: "CONNECTING",
  LIVE: "LIVE",
  RECOVERING: "RECOVERING",
  OFFLINE: "OFFLINE",
  ENDED: "ENDED",
  ERROR: "ERROR",
});
