spring.application.name=Quiz_Wheelz

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/quiz_wheelz?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jerusalem
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# JWT
app.jwt.secret=CHANGE_ME_TO_A_LONG_SECRET_KEY_AT_LEAST_32_CHARS
app.jwt.expiration-ms=86400000

# Auth Cookie בפרודוקשון לשנות SECURE=true
app.auth.cookie-name=AUTH_TOKEN
app.auth.cookie-max-age-seconds=86400
app.auth.cookie-secure=false
app.auth.cookie-same-site=Lax