export const RACE_STATUSES = Object.freeze({
    WAITING_FOR_PLAYERS: "WAITING_FOR_PLAYERS",
    READY: "READY",
    IN_PROGRESS: "IN_PROGRESS",
    FINISHED: "FINISHED",
    CANCELLED: "CANCELLED",
});

export const RACE_STATUS_LABELS = Object.freeze({
    [RACE_STATUSES.WAITING_FOR_PLAYERS]: RACE_STATUSES.WAITING_FOR_PLAYERS,
    [RACE_STATUSES.READY]: RACE_STATUSES.READY,
    [RACE_STATUSES.IN_PROGRESS]: RACE_STATUSES.IN_PROGRESS,
    [RACE_STATUSES.FINISHED]: RACE_STATUSES.FINISHED,
    [RACE_STATUSES.CANCELLED]: RACE_STATUSES.CANCELLED,
});

export const RACE_STATUS_BADGE_CLASSES = Object.freeze({
    [RACE_STATUSES.WAITING_FOR_PLAYERS]: "bg-amber-100 text-amber-700",
    [RACE_STATUSES.READY]: "bg-emerald-100 text-emerald-700",
    [RACE_STATUSES.IN_PROGRESS]: "bg-sky-100 text-sky-700",
    [RACE_STATUSES.FINISHED]: "bg-slate-200 text-slate-700",
    [RACE_STATUSES.CANCELLED]: "bg-rose-100 text-rose-700",
});

export const EDITABLE_RACE_STATUSES = Object.freeze([
    RACE_STATUSES.WAITING_FOR_PLAYERS,
    RACE_STATUSES.READY,
]);

export const CANCELLABLE_RACE_STATUSES = Object.freeze([
    RACE_STATUSES.WAITING_FOR_PLAYERS,
    RACE_STATUSES.READY,
]);
