export const SERVER_ERROR_NAMES = Object.freeze({
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  UNAUTHORIZED: "UNAUTHORIZED",

  VALIDATION_ERROR: "VALIDATION_ERROR",

  RACE_NOT_FOUND: "RACE_NOT_FOUND",
  RACE_NOT_JOINABLE: "RACE_NOT_JOINABLE",
  RACE_FULL: "RACE_FULL",
  RACE_PLAYER_NAME_TAKEN: "RACE_PLAYER_NAME_TAKEN",

  RACE_PLAYER_TOKEN_MISSING: "RACE_PLAYER_TOKEN_MISSING",
  INVALID_RACE_PLAYER_TOKEN: "INVALID_RACE_PLAYER_TOKEN",
  RACE_PLAYER_NOT_FOUND: "RACE_PLAYER_NOT_FOUND",

  RACE_PLAYER_NOT_RACING: "RACE_PLAYER_NOT_RACING",
  RACE_NOT_IN_PROGRESS: "RACE_NOT_IN_PROGRESS",

  QUESTION_EXPIRED: "QUESTION_EXPIRED",

  QUESTION_NOT_ACTIVE: "QUESTION_NOT_ACTIVE",
  QUESTION_NOT_FOUND_FOR_PLAYER: "QUESTION_NOT_FOUND_FOR_PLAYER",
  QUESTION_CHOICE_NOT_FOUND: "QUESTION_CHOICE_NOT_FOUND",

  RACE_PLAYER_RECONNECT_WINDOW_EXPIRED: "RACE_PLAYER_RECONNECT_WINDOW_EXPIRED",
  RACE_PLAYER_RECONNECT_REQUIRED: "RACE_PLAYER_RECONNECT_REQUIRED",

  RACE_RESULTS_NOT_AVAILABLE: "RACE_RESULTS_NOT_AVAILABLE",
});
