export const RACES_PREVIEW_LIMIT = 5;

export const WORKSPACE_NAVBAR_WIDTH = 280;

export const WORKSPACE_MOBILE_BREAKPOINT = "sm";

export const WORKSPACE_LIVE_RACE_BREAKPOINT = "lg";

export const WORKSPACE_MOBILE_HEADER_HEIGHT = 56;
